name: Update MTG Data
on:
  schedule:
    - cron: '0 0 * * *'  # Run daily
  workflow_dispatch:
  push:

jobs:
  update-data:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.15'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Clone MTGODecklistCache
      #   run: |
      #     cd ../
      #     git clone https://github.com/Badaro/MTGODecklistCache.git
      #     cd -

      - name: Clone Processed
        run: |
          cd ../
          git clone https://github.com/ArcKayNine/UrzasResearchDesk_Processing.git
          cd -
          cp ../UrzasResearchDesk_Processing/*.zip docs/
          
      - name: Build WASM
        run: |
          ./bundle.sh
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: ./docs